lst_scripts/run_hiperta_reorg_output.py

script to run full hiperta and reorganize

---

lst_scripts/run_onsite_mc_merge_and_dl1_to_dl2.py

script to merge and run dl1 to dl2 on La Palma

---

lst_scripts/reorganize_dl1_files.py

add reorganized dl1 to this repository - same version as HiPeCTA -. It does include the computation of disp_* params and mc_type

add reorganized dl1 to this repository too

---

lst_scripts/reorganize_dl1_output_files_hiperta_hipecta.py
lst_scripts/run_onsite_hiperta_mc_merge_and_dl1_to_dl2.py
lst_scripts/run_onsite_mc_merge_and_dl1_to_dl2.py

working version at LaPalma for the script run_onsite_mc_merge_and_dl1_to_dl2.py

---

lst_scripts/onsite_mc_train.py

.replace() is case sensitive and a path needed to be changed

---

lst_scripts/core_list.sh
lst_scripts/data_management.py
lst_scripts/lstchain_standard_config_v050.json
lst_scripts/onsite_mc_dl1_to_dl2.py
lst_scripts/onsite_mc_merge_and_copy_dl1.py
lst_scripts/onsite_mc_r0_to_dl1.py
lst_scripts/onsite_mc_r0_to_dl3.py
lst_scripts/onsite_mc_train.py
lst_scripts/reorganize_dl1hiperta_to_dl1lstchain.py
lst_scripts/workflow_management.py

- Add `lstchain_standard_config_v050.json`
- Adapt arguments key to v0.5.0
- Update `reorganize_dl1hiperta_to_dl1lstchain.py`
- Manages source environment in `r0_to_dl1` stage. Resolves #32

Update to lstchain v050

---

lst_scripts/onsite_mc_merge_and_copy_dl1.py
lst_scripts/onsite_mc_r0_to_dl3.py
lst_scripts/workflow_management.py

Issue solver

---

lst_scripts/hiperta_standard_config.txt
lst_scripts/lstchain_standard_config_v052.json
lst_scripts/onsite_mc_dl1_to_dl2.py
lst_scripts/onsite_mc_merge_and_copy_dl1.py
lst_scripts/onsite_mc_r0_to_dl1.py
lst_scripts/onsite_mc_r0_to_dl3.py
lst_scripts/onsite_mc_train.py
lst_scripts/workflow_management.py

- yml log; resolves #27  
- Creates `log_machine_STAGE_prod_id.txt` files with certain information about the machine used, resolves #42 
- Update hiperta standard config (should not be done here, I know)

Add yaml log

---

lst_scripts/onsite_mc_dl1_to_dl2.py
lst_scripts/onsite_mc_merge_and_copy_dl1.py
lst_scripts/onsite_mc_r0_to_dl3.py
lst_scripts/workflow_management.py

- Resolves #36
- correct format bug in log dump that was not logging all the jobids
- clean code from last yml implementation
- Take out old log .txt file (substituted by yml)

Clean yml implementation

---

lst_scripts/data_management.py
lst_scripts/hiperta_r0_to_dl1lstchain.py
lst_scripts/reorganize_dl1hiperta_to_dl1lstchain.py

Make the reorganiser script independent of `lstchain`, so that the `hiperta + reorganizer` part can be run in a environment without `lstchain`.

Hiperta independent lstchain

---

lst_scripts/onsite_mc_merge_and_copy_dl1.py
lst_scripts/onsite_mc_r0_to_dl3.py
lst_scripts/workflow_management.py

And add of missing -e and -o jobs for merging

log can be load into a single dict

---

lst_scripts/config_MC_prod.yml
lst_scripts/data_management.py
lst_scripts/onsite_mc_dl1_to_dl2.py
lst_scripts/onsite_mc_merge_and_copy_dl1.py
lst_scripts/onsite_mc_r0_to_dl1.py
lst_scripts/onsite_mc_train.py
lst_scripts/workflow_management.py

Resolves #69 and #48 
- It also cleans the old `--exclude=cp13`, 
- put all `r0_to_dl1` jobs in long queue and limits the number of batched jobs

Correct files per dl1 job

---

README.rst
lst_scripts/config_MC_prod.yml
lst_scripts/onsite_mc_dl1_to_dl2.py
lst_scripts/onsite_mc_dl2_to_irfs.py
lst_scripts/onsite_mc_r0_to_dl1.py
lst_scripts/onsite_mc_r0_to_dl3.py
lst_scripts/workflow_management.py

dl2_to_irfs stage in the MC prod workflow

---

lstmcpipe/batch_dl1_utils-merge_and_copy.py
lstmcpipe/config_MC_prod.yml
lstmcpipe/onsite_mc_dl2_to_irfs.py
lstmcpipe/onsite_mc_hiperta_r0_to_dl1lstchain.py
lstmcpipe/onsite_mc_merge_and_copy_dl1.py
lstmcpipe/onsite_mc_r0_to_dl3.py
lstmcpipe/workflow_management.py

at a time, instead of creating a single one per MC prod

Create all irfs

---

lstmcpipe/hiperta/reorganize_dl1hiperta300_to_dl1lstchain060.py

In some hiperta casses, the reorganiser will be called as a script

make reorganizer callable

---

lstmcpipe/hiperta/reorganize_dl1hiperta300_to_dl1lstchain060.py

see:
https://gitlab.in2p3.fr/CTA-LAPP/rta/HiPeRTA_Stream/-/merge_requests/5/diffs

fix path to images in DL1 files

---

README.rst
lstmcpipe/config_MC_prod.yml
lstmcpipe/onsite_mc_r0_to_dl3.py
lstmcpipe/tests/test_workflow_management.py
lstmcpipe/workflow_management.py

Suggested by @chaimain (thanks !),
- Move the `--no-image` argument in the `onsite_mc_r0_to_dl3` script to the `config_MC_prod.yml` file. Change the script argument by an entry in the configuration file.
Also;
- Quickstart and launch workflow explanations clarified in the README.
- Started some unit tests.

No image arg to config file

---

lstmcpipe/stages/mc_r0_to_dl1.py

for r0dl1 stage.
Last prod give timeout error for electrons. After this new prod we will change it if needed.

put all particle under long queue

---

lstmcpipe/scripts/script_dl2_to_sensitivity.py

argument outfile can't  be '.'  as default

Update default outfile in script_dl2_to_sensitivity.py

---

README.rst
lstmcpipe/logging.py
lstmcpipe/lstmcpipe_start.py

Small updates to improve the documentation:
- Updated README (replacing out of date instructions, more installation instructions, adding my own contact information)
- Add some docstrings

Documentation

---

codemeta.json

@garciagenrique @LukasNickel maybe you can add your author information  as  well in the file please - by pushing directly to this PR branch is fine

Adding codemeta.json file for standard metadata

---

lstmcpipe/stages/mc_dl1_to_dl2.py

remove dl1_to_dl2 training file from list of file to be processed

---

lstmcpipe/hiperta/hiperta_r0_to_dl1lstchain.py
lstmcpipe/scripts/tests/test_scripts.py
setup.py

invoke - at least -  the help of all installed scripts

Test scripts are installed correctly 

---

lstmcpipe/stages/mc_dl1_to_dl2.py
lstmcpipe/stages/mc_train.py

Last prod complained on all these stages due to lack of memory. 
Requesting more than expected, but it is a pain relaunching the stages manually.

add mem requirements to stages

---

lstmcpipe/config/pipeline_config.py
lstmcpipe/stages/mc_process_dl1.py

Everything in a single commit... (my bad, wanted to do many things at the same time)
- take out all capital letters 
- substitute os.path by Path 
- clarify dl1_files_per_job argument

reformat dl1_process_dl1.py

---

lstmcpipe/stages/mc_process_dl1.py

improve if else cases with dl1_files_per_job

---

lstmcpipe/config/pipeline_config.py
lstmcpipe/config/tests/test_config.py
lstmcpipe/config_MC_prod.yml
lstmcpipe/lstmcpipe_start.py
lstmcpipe/stages/mc_dl1_to_dl2.py
lstmcpipe/stages/mc_dl2_to_irfs.py
lstmcpipe/stages/mc_dl2_to_sensitivity.py
lstmcpipe/stages/mc_merge_and_copy_dl1.py
lstmcpipe/stages/mc_process_dl1.py
lstmcpipe/stages/mc_train.py
lstmcpipe/workflow_management.py

Allow selecting the slurm account when batching a production

Slurm config account

---

lstmcpipe/stages/mc_dl1_to_dl2.py

Same as https://github.com/cta-observatory/cta-lstchain/pull/927

replace "dl1" for "dl2" string only in test dataset

---

lstmcpipe/config/__init__.py
lstmcpipe/config/dl1ab_tuning.py
lstmcpipe/config/pipeline_config.py
lstmcpipe/config_MC_dl1ab_prod.yml
lstmcpipe/config_MC_prod.yml
lstmcpipe/lstmcpipe_start.py

Add config keys that trigger the use of `lstchain_tune_nsb` in order to get the image modifier settings for a given observation run.
That should eliminate one step got getting matching monte carlo

Add noise fine tuning

---

lstmcpipe/config/paths_config.py

protons appear in both `training` and `testing` and an extra path (repeated protons) appeared everywhere

avoid `particles` are repeated

---

lstmcpipe/config/paths_config.py
lstmcpipe/config/pipeline_config.py
lstmcpipe/config/tests/test_paths_config.py
lstmcpipe/config/tests/test_pipeline_config.py
lstmcpipe/io/data_management.py
lstmcpipe/lstmcpipe_start.py
lstmcpipe/scripts/script_train_test_splitting.py
lstmcpipe/stages/mc_dl1_to_dl2.py
lstmcpipe/stages/mc_dl2_to_irfs.py
lstmcpipe/stages/mc_dl2_to_sensitivity.py
lstmcpipe/stages/mc_merge_dl1.py
lstmcpipe/stages/mc_process_dl1.py
lstmcpipe/stages/mc_train.py
lstmcpipe/stages/mc_train_test_splitting.py

Fixes quite some issues with the stages and the config, and how information flows in the different stages.
The pipeline now runs (or seems to) from R0 to IRFs but only 1 DL1 is produced 😅 
So some more work to do...

Fix stages and config

---

lstmcpipe/stages/mc_train.py

small bugs found after making train_pipe "paralelizable"

fix batch_plot_rf_feat

---

lstmcpipe/__init__.py
lstmcpipe/io/lstmcpipe_tree_path.py
lstmcpipe/io/tests/test_lstmcpipe_tree_path.py
setup.py

environment variable LSTMCPIPE_PROD_LOGS if defined, else in `$HOME/LSTMCPIPE_PROD_LOGS`

set prod_logs variable

---

lstmcpipe/scripts/generate_test_lapalma.py

Small script to generate a mini prod tree on the cluster with its paths config

Test prod script

---

lstmcpipe/config/paths_config.py

dl1 to dl2 should give output dir

---

.github/workflows/pypi.yml

automated pypi publication when making a new release

add pypi publish action

---

.github/workflows/docs.yml
docs/conf.py
docs/produce_config_page.py

Fixes #201 
Solution taken from https://github.com/actions/checkout/issues/468

Prod dates in doc

---

lstmcpipe/config/paths_config.py
lstmcpipe/stages/mc_dl1_to_dl2.py
lstmcpipe/stages/mc_dl2_to_irfs.py
lstmcpipe/stages/mc_dl2_to_sensitivity.py
lstmcpipe/stages/mc_merge_dl1.py
lstmcpipe/stages/mc_process_dl1.py
lstmcpipe/stages/mc_train.py
lstmcpipe/stages/mc_train_test_splitting.py

Slurm options would need to be passed to PathConfig by creating a child class in where the user will define the slurm options for each stage.

add slurm options for each stage set

---

lstmcpipe/config/paths_config.py
lstmcpipe/scripts/generate_test_lapalma.py

AllSky config refactoring to separate training and testing and run on all declinations

---

lstmcpipe/lstmcpipe_start.py
lstmcpipe/stages/mc_dl2_to_irfs.py
lstmcpipe/stages/mc_dl2_to_sensitivity.py
lstmcpipe/stages/mc_merge_dl1.py
lstmcpipe/stages/mc_train.py

fix dependency issues

---

production_configs/20220518_allsky_dec2276_tuned/README.md
production_configs/20220518_allsky_dec2276_tuned/generate.py
production_configs/20220518_allsky_dec2276_tuned/lstchain_config_dec_2276_tuned.json
production_configs/20220518_allsky_dec2276_tuned/lstmcpipe_config_20220518_allsky_dec2276_tuned.yml

lstchain config provided by  @moralejo

config for prod 20220518_allsky_dec2276_tuned

---

lstmcpipe/scripts/script_batch_filelist_cta.py
lstmcpipe/scripts/script_batch_filelist_lst.py
lstmcpipe/scripts/script_batch_filelist_lst_dl1ab.py
lstmcpipe/scripts/script_batch_filelist_rta.py

- This should now restore offline use @garciagenrique (Fixes #147 )
- Updated black in the pre commit hook as it clashes with click (https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click). But we should update from time to time anyway

Use core scripts outside the job array

---

lstmcpipe/config/paths_config.py
lstmcpipe/plots/pointings.py

fix issue with plot_pointings projections

---

lstmcpipe/scripts/lstmcpipe_generate_config.py
lstmcpipe/utils.py

To (try to) avoid error leading to #280 again
Fixes #291 
I knew I fixed that 😂

Improve lstchain config dumping

---

production_configs/20220523_dec_413_tuned_nsb/lstchain_config_2022-05-23.json
production_configs/20220523_dec_413_tuned_nsb/lstmcpipe_config_2022-05-23_PathConfigAllSkyFullDL1ab.yaml
production_configs/20220523_dec_413_tuned_nsb/readme.md

Hi! 
I just followed instructions to create lstmcpipe config files for running dl1ab steps on a dec_413 production  for getting NSB tuned MCs. 
I also produced the lstchain config and added the NSB tuning parameters.
I added by hand to the RF features the "sin_az_tel" and "alt_tel". I'm not sure if it should be "sin_az_tel" or just "az_tel", (I followed this https://github.com/cta-observatory/cta-lstchain/pull/977). According also to that pull, should I change the time_gradient and skewness for the signed version of those parameters? Tell me if I should change anything and I will update the PR.
Thanks a lot!

Add configuration for source dec 413 and tuned nsb

---

docs/produce_config_page.py

add readmes to the prod table

---

production_configs/20220523_dec_413_tuned_nsb/lstchain_config_2022-05-23.json
production_configs/20220523_dec_413_tuned_nsb/lstmcpipe_config_2022-05-23_PathConfigAllSkyFullDL1ab.yaml
production_configs/20220523_dec_413_tuned_nsb/readme.md

I corrected the problems in the lstchain config file that was causing the production launching to fail: add missing commas, add missing parameter increase_psf

Correct lstchain config file problems for min413 production with nsb tuning

---

environment.yml

following PR https://github.com/cta-observatory/cta-lstchain/pull/943

fix error  with protobuf

---

.pre-commit-config.yaml

and running a `pre-commit autoupdate`

Update .pre-commit file with new flake8 repo

---

production_configs/20221006_src3_test_nodes/README.md
production_configs/20221006_src3_test_nodes/lstchain_config_2022-10-06.json
production_configs/20221006_src3_test_nodes/lstmcpipe_config_2022-10-06_PathConfigAllSkyTestingDL1ab.yaml

20221006_src3_test_nodes
produce Test DL1 datasets including newly produced test MCs (`theta_23.630_az_100.758` and `theta_23.630_az_259.265`)
This production config includes only DL1ab and DL1 merge process

20221006 src3 test nodes

---

production_configs/20221025_src4_high_NSB_LZA/lstchain_config_2022-10-25.json
production_configs/20221025_src4_high_NSB_LZA/lstmcpipe_config_2022-10-25_PathConfigAllSky_LZA.yaml
production_configs/20221025_src4_high_NSB_LZA/readme.md

20221025_src4_high_NSB_LZA
src4_high_NSB_LZA
This config processes the src4 test and training file at LZA (zd>52 deg) with correct NSB (after bug correction) and with the new MC production files ([https://github.com/cta-observatory/lst-sim-config/issues/50](https://github.com/cta-observatory/lst-sim-config/issues/50))
To improve the src4 LZA simulation

Request new production for src4

---

production_configs/20221025_src4_high_NSB_LZA/lstchain_config_2022-10-25.json

adding psf tuning False to config

---

production_configs/20221108_galsource_min_413_tuned_nsb/lstchain_config_2022-11-08.json
production_configs/20221108_galsource_min_413_tuned_nsb/lstmcpipe_config_2022-11-08_PathConfigAllSkyFullDL1ab.yaml
production_configs/20221108_galsource_min_413_tuned_nsb/readme.md

20221108_galsource_min_413_tuned_nsb
dec_min_413 with NSB tuning to galactic source.
Reprocess with the latest version of lstchain v0.9.9. Previous prod_id is `galsource_min_413_tuned_nsb`.
RF features following issue #369
```
lstmcpipe_generate_config PathConfigAllSkyFullDL1ab --prod_id 20221108_galsource_min_413_tuned_nsb --kwargs source_prod_id=20221027_v0.9.9_base_prod --dec_list dec_min_413
```

Run prod. 20221108_galsource_min_413_tuned_nsb

---

production_configs/20221104_src3_dec3476_4822_tuned/README.md
production_configs/20221104_src3_dec3476_4822_tuned/lstchain_config_2022-11-04.json
production_configs/20221104_src3_dec3476_4822_tuned/lstmcpipe_config_2022-11-04_PathConfigAllSkyFullDL1ab.yaml

20221104_src3_dec3476_4822_tuned
dec3476 and dec4822 with NSB tuning
reprocess with the latest version of lstchain v0.9.9

20221104 src3 dec3476 4822 tuned

---

lstmcpipe/scripts/script_lstmcpipe_validate_config.py
lstmcpipe/utils.py

image_extractor was correctly dumped, but not validated.
Production "20221128_src5_dec3476_tuned" #375 is probably not valid

validate lstchain config for mc requirements on image extractor

---

production_configs/20230329_v0.9.13_src4_full_line/lstmcpipe_config_2023-03-29_PathConfigAllSkyFull.yaml

Fixing memory issue for job dl1_to_dl2 in prod 20230329_v0.9.13_src4_full_line
FYI @FrancaCassol

Fixing memory issue in prod

---

.github/workflows/pypi.yml

pypi github workflow

---

production_configs/20230921_v0.10.4_src3_dec3476_4822_tuned/lstchain_config_2023-09-21.json
production_configs/20230921_v0.10.4_src3_dec3476_4822_tuned/lstmcpipe_config_2023-09-21_PathConfigAllSkyFullDL1ab.yaml
production_configs/20230921_v0.10.4_src3_dec3476_4822_tuned/readme.md

Duplicate of #422 to allow download data to pass (it needs the secret which is in this repo).
Closes #422

20230921 v0.10.4 src3 dec3476 4822 tuned from Seiya

---

production_configs/20230925_v0.10.4_src3_dec3476_4822_tuned/lstchain_config_2023-09-25.json
production_configs/20230925_v0.10.4_src3_dec3476_4822_tuned/lstmcpipe_config_2023-09-25_PathConfigAllSkyFullDL1ab.yaml
production_configs/20230925_v0.10.4_src3_dec3476_4822_tuned/readme.md

reproduce prod 20230921_v0.10.4_src3_dec3476_4822_tuned with missing dl1 to dl2

---

production_configs/20230927_v0.10.4_crab_tuned/lstchain_config_2023-09-27.json
production_configs/20230927_v0.10.4_crab_tuned/lstmcpipe_config_2023-09-27_PathConfigAllSkyFullDL1ab.yaml
production_configs/20230927_v0.10.4_crab_tuned/readme.md

add production_configs/20230927_v0.10.4_crab_tuned/

---

production_configs/20231017_v0.10.4_seasonal_atmospheres_summer/20231017_v0.10.4_seasonal_atmospheres_summer_full.yaml
production_configs/20231017_v0.10.4_seasonal_atmospheres_summer/lstchain_config_2023_10_17.json
production_configs/20231017_v0.10.4_seasonal_atmospheres_summer/readme.md

Voutsi seasonal atmosphere

---

docs/pipeline.rst
lstmcpipe/config/paths_config.py

New Path Config to restart from DL1b files and do train+test

path config for a train-test analysis from existing prod

---

environment.yml

Update environment.yml to remove constraints on versions

---

production_configs/20240828_v0.10.9_GC_dec_min_2924_tuned/README.md
production_configs/20240828_v0.10.9_GC_dec_min_2924_tuned/lstchain_config_2024-08-28.json
production_configs/20240828_v0.10.9_GC_dec_min_2924_tuned/lstmcpipe_config_2024-08-28_PathConfigAllSkyFull.yaml

20240828_v0.10.9_GC_dec_min_2924_tuned

my_20240828_branch

---

lstmcpipe/config/paths_config.py
lstmcpipe/scripts/generate_nsb_levels_configs.py

split gamma diffuse in train/test with new child configs

---

lstmcpipe/config/paths_config.py

fix test DL2 and IRF paths including particle type to separate Gamma and GammaDiffuse
Fixes #493

fix test DL2 and IRF paths

---

docs/produce_config_page.py
docs/productions.rst
docs/requirements.txt
production_configs/20240529_v0.10.11_src4_dense_MC_line/readme.md
production_configs/20240821_v0.10.11_src14_dec2276_tuned/README.md
production_configs/20240828_v0.10.9_GC_dec_min_2924_tuned/README.md
production_configs/20240917_v0.10.12_src15_dec_min_2924_tuned/README.md

readmes are now in individual cards to improve readability

Improved productions table formatting

---

production_configs/20250616_v0.11.0_LZA_investigation/lstmcpipe_config.yml

Fix the lstchain version issue of #520

20250616_v0.11.0_LZA_investigation fix lstchain version
