lstmcpipe/onsite_mc_dl2_to_irfs.py
Add gamma type - point like or diffuse, and the gamma_offset to the output filename. Otherwise, this info is only recovered either from the config or the cmd sent to slurm.
=> IRFs output filename

lstmcpipe/hiperta/reorganize_dl1hiperta300_to_dl1lstchain060.py
correct event.telescope.image path on lstchain compliant output file
=> path to images in reorganized dl1 (lstchain-like) is wrong

lstmcpipe/hiperta/reorganize_dl1hiperta300_to_dl1lstchain060.py
Again mix with  `image` and `images` key for the ctapipe and lstchain data models....
ctapipe: `/dl1/event/telescope/images/tel_001` [doc](https://github.com/cta-observatory/cta-lstchain/blob/deabb5c3de058954028ead129d2368d2b70404ed/lstchain/io/io.py#L58)
lstchain: `/dl1/event/telescope/image/LST_LSTCam` [doc](https://github.com/cta-observatory/cta-lstchain/blob/deabb5c3de058954028ead129d2368d2b70404ed/lstchain/io/io.py#L58)
=> update RTA reorganiser with correct paths

lstmcpipe/stages/mc_process_dl1.py
Computing time sometimes depends on the machine.
electrons and point like gammas should be running on short, but sometimes they run on timeout at the cluster
=> change all partitions to long

lstmcpipe/config/paths_config.py
I think it makes much more sense now to organise the tree production wise, and so to have:
```
data/mc/
└── AllSky
└── DL0
├── TestDataset
└── TrainingDataset
└── DL1
├── TestDataset
└── TrainingDataset
└── DL2
├── TestDataset
└── TrainingDataset
```
rather than
```
data/mc/
├── DL0
│   └── AllSky
├── DL1
│   └── AllSky
├── DL2
│   └── AllSky
```
=> Modify AllSky tree

docs/conf.py, docs/index.rst, docs/pipeline.rst, docs/requirements.txt
Add a documentation page with the pipeline graph:
```mermaid
graph LR
subgraph R0
gamma
proton
electron
end
gamma --> r0dl1((r0_to_dl1))
proton --> r0dl1
electron --> r0dl1
subgraph DL1
gamma_dl1
proton_dl1
electron_dl1
end
r0dl1 --> gamma_dl1[DL1 gamma]
r0dl1 --> proton_dl1[DL1 proton]
r0dl1 --> electron_dl1[DL1 electron]
gamma_dl1 --> train_test_split((train_test_split))
proton_dl1 --> train_test_split
train_test_split --> DL1train[DL1 train]
train_test_split --> DL1test[DL1 test]
DL1train --> train_pipe((train_pipe))
train_pipe --> models
electron_dl1 --> DL1test
DL1train --> |dl1ab| DL1train
DL1test --> |dl1ab| DL1test
models --> DL2
DL1test --> DL2[DL2 test]
DL2 --> |dl2_to_irf| IRF[IRFs]
DL2 --> |dl2_to_sensitivity| SENS[Sensitivity]
SENS --> plot[png plots]
```
Can be completed …
=> add doc page with pipelines

lstmcpipe/config/paths_config.py
A few (3) dl1_to_dl2 jobs failed to lack of RAM.
This raises the requirement to be on the safe side.
In the future, lstchain should require less memory with the refactoring of the RFs application.
=> Raise memory requirement to 60GB by default

production_configs/20220905_src4_high_NSB/lstchain_config_2022-09-05.json, production_configs/20220905_src4_high_NSB/lstmcpipe_config_2022-09-05_PathConfigAllSkyFull.yaml, production_configs/20220905_src4_high_NSB/readme.md
Config for a source src4 with dec 6166 and NSB tuning described in the config file
```
lstmcpipe_generate_config  PathConfigAllSkyFull --prod_id 20220905_src4_high_NSB --dec_list dec_6166
``` 
@FrancaCassol could you confirm that you used the above command to generate the config, please ?
=> add 20220905_src4_high_NSB prod files

lstmcpipe/config/paths_config.py, lstmcpipe/scripts/generate_test_lapalma.py, lstmcpipe/scripts/useful_tmp_scripts/rerun_irfs_mem_issue.py, lstmcpipe/stages/mc_dl1_to_dl2.py, lstmcpipe/stages/mc_dl2_to_irfs.py, lstmcpipe/stages/mc_dl2_to_sensitivity.py, lstmcpipe/stages/mc_merge_dl1.py, lstmcpipe/stages/mc_process_dl1.py, lstmcpipe/stages/mc_train.py, lstmcpipe/stages/mc_train_test_splitting.py, lstmcpipe/tests/test_utils.py, lstmcpipe/utils.py
The main changes concerns the slurm options in `SbatchLstMCStage` and config files.
These options are now handled as dictionnaries,  allowing more flexibility and clarity.
The "general" options (account, error or output files...) are still set on their own but can be overwritten by specific slurm options in some stages.
Default options are easily overwritten too, but the user does not need to specify the full extent of them as it was the case before.
=> default options before all other options

production_configs/20220913_crab_theta23_tuned/README.md, production_configs/20220913_crab_theta23_tuned/lstchain_config_dec_2276_tuned.json, production_configs/20220913_crab_theta23_tuned/lstmcpipe_config_20220913_crab_theta23_tuned.yml
Following production `20220902_crab_test_nodes` that had no tuning.
Processing of nodes node_theta_23.630_az_100.758 and node_theta_23.630_az_259.265_ only for:
- dl1ab
-  with tuned config from [crab tuned prod](https://github.com/cta-observatory/lstmcpipe/blob/master/production_configs/20220518_v0.9.6_allsky_dec2276_tuned/lstchain_config_dec_2276_tuned.json)
- merge
- dl1_to_dl2
- with trained RF from crab tuned prod: `/fefs/aswg/data/models/AllSky/20220518_allsky_dec2276_tuned/dec_2276`
- dl2_to_irfs
See https://github.com/cta-observatory/lst-sim-config/issues/49#issuecomment-1235392024
=> 20220913 crab theta23 tuned

lstmcpipe/config/paths_config.py
When MC nodes are added between production, or if a former prod included only a subset of nodes, it's still fine to be able to run a DL1ab stage on it.
Warn user and remove nodes that won't be included in the production rather than raising a blocking `FileNotFoundError` in DL1ab prods.
=> Smarter prod dl1ab checker

production_configs/20221128_src5_dec3476_tuned/lstchain_config_20221128_src5_dec3476_tuned.json, production_configs/20221128_src5_dec3476_tuned/lstmcpipe_config_2022-11-28_PathConfigAllSkyFullDL1ab.yaml, production_configs/20221128_src5_dec3476_tuned/readme.md
20221128_src5_dec3476_tuned
dec_3476 with NSB tuning to src5 and src-dependent configuration.
Reprocess the data at declination 34.76 with version of lstchain v0.9.9 and with new tunning for new source: src5.
=> New production config 20221128_src5_dec3476_tuned

production_configs/20221215_v0.9.12_base_prod/lstchain_config.json, production_configs/20221215_v0.9.12_base_prod/lstmcpipe_config.yml, production_configs/20221215_v0.9.12_base_prod/readme.md
- [ x] I have checked the lstchain config, in particular for:
- [ x] `az_tel` instead of `sin_az_tel` if data to be analyzed have been produced with lstchain <= v0.9.7
- [ x] "increase_nsb" and "increase_psf" are provided in "image_modifier" (if used)
- [ x] I have checked the environment in the lstmcpipe config and it is the one used to analyse DL>1 data
- [ x] I have provided the command (in README), or script (in additionnal .py file) used to produce the lstmcpipe config
20221215_v0.9.12_base_prod
Standard NSB standard PSF for processing standard AGN dark data. 
Declination tracks needed:
- dec_2276 
- dec_3476 
- dec_4822 
- dec_6676 
- dec_931
- dec_min_413 
While some sources may require tuned NSB, I want to check myself how an incorrect NSB spoils the …
=> Add full production with standard NSB/PSF for AGN analysis

lstmcpipe/tests/test_utils.py, lstmcpipe/utils.py
=> make sure that all jobs check the exit code before continuing

lstmcpipe/tests/test_utils.py, lstmcpipe/utils.py
=> the dependencies afterok should be given with :

production_configs/20221215_v0.9.12_base_prod/readme.md, production_configs/20230127_v0.9.12_base_prod_az_tel/readme.md, production_configs/20230414_v0.9.13_dec_931_az_tel/README.md, production_configs/20230414_v0.9.13_dec_931_az_tel/lstchain_config.json, production_configs/20230414_v0.9.13_dec_931_az_tel/lstmcpipe_config.yml
Reprocessing of faulty dec_931.
This production should be used instead of `20230127_v0.9.12_base_prod_az_tel` for dec_931.
=> new prod 20230414_v0.9.13_dec_931_az_tel to fix dec_931 issue

production_configs/20230601_v0.9.13_dec_4822_dec_6166/lstchain_config_2023-06-01.json, production_configs/20230601_v0.9.13_dec_4822_dec_6166/lstmcpipe_config_2023-06-01_PathConfigAllSkyFull.yaml, production_configs/20230601_v0.9.13_dec_4822_dec_6166/readme.md
20230601_v0.9.13_dec_4822_dec_6166
Create a production with lstchain-v0.9.13 with all testing nodes for dec_4822 and dec_6166 with sin_az_tel. The stage r0_to_dl1 is the only stage used because this production will be used as the base prod. to latter tune the NSB.
Processing of source 7 with MC processed with lstchain-v0.9.13 for dec. bands dec_4822 and dec_6166 with all available testing nodes.
=> 20230601 v0.9.13 dec 4822 dec 6166

codemeta.json, lstmcpipe/stages/mc_process_dl1.py
When the lstmcpipe is run using the dl1ab step, the workflow_step label `r0_to_dl1` appears instead of the `dl1ab` in the log_reduced*.yml and log_lstmcpipe_*.yml files.
This PR should fix this bug.
=> Bug: fix workflow_step label in log files when dl1ab step is used

production_configs/20230829_src5_dec3476_v0.10_tuned/lstchain_config_20230829_src5_dec3476_v0.10_tuned.json, production_configs/20230829_src5_dec3476_v0.10_tuned/lstmcpipe_config_2023-08-29_PathConfigAllSkyFull.yaml, production_configs/20230829_src5_dec3476_v0.10_tuned/readme.md
20230829_src5_dec3476_v0.10_tuned 
=> Add new production src5 with lstchain v0.10

production_configs/20230901_v0.10.4_allsky_base_prod/README.md, production_configs/20230901_v0.10.4_allsky_base_prod/lstchain_config_2023-09-01.json, production_configs/20230901_v0.10.4_allsky_base_prod/lstmcpipe_config_2023-09-01_PathConfigAllSkyFull.yaml
All grid nodes with default settings and lstchain 0.10.4.
There have been datamodel-changes in the transition from lstchain 0.9 to 0.10, which is why a new production is in order.
Also old `lstchain` configs dont necessarily work with the new versions (e.g. due to floating point `verbose` values).
This request includes all declination lines and no NSB-tuning in order to act as a new baseline.
For the same reason all processing steps are included.
That should make it possible to directly compare the performance to the older `20230127_v0.9.12_base_prod_az_tel` production.
For Crab or other high-NSB sources, a `dl1ab` reprocessing or another prodcution will thus be needed.
I personally can not make use of all the grid lines, but I figured it would be useful to have them …
=> Add configs for new allsky production using lstchain 0.10.4

production_configs/20231106_v0.9.12_base_dl1_dec_931_min-2924_min-1802_6166/README.md, production_configs/20231106_v0.9.12_base_dl1_dec_931_min-2924_min-1802_6166/lstchain_config.json, production_configs/20231106_v0.9.12_base_dl1_dec_931_min-2924_min-1802_6166/lstmcpipe_config_2023-11-06_PathConfigAllSkyFull.yaml
Base DL1 prod for missing declination in `20221215_v0.9.12_base_prod`
```
lstmcpipe_generate_config PathConfigAllSkyFull --prod_id 20231106_v0.9.12_base_dl1_dec_931_min-2924_min-1802_6166 --dec_list dec_931 dec_min_2924 dec_min_1802 dec_6166
```
=> prod 20231106_v0.9.12_base_dl1_dec_931_min-2924_min-1802_6166

production_configs/20240131_allsky_v0.10.5_all_dec_base/README.md, production_configs/20240131_allsky_v0.10.5_all_dec_base/lstchain_config_2024-01-31.json, production_configs/20240131_allsky_v0.10.5_all_dec_base/lstmcpipe_config_2024-01-31_PathConfigAllSkyFull.yaml
Base production for all declinations lines with lstchain v0.10.5
```
lstmcpipe_generate_config PathConfigAllSkyFull --prod_id 20240131_allsky_v0.10.5_all_dec_base --dec_list dec_2276 dec_4822 dec_6166 dec_6676 dec_min_1802 dec_min_413
```
contact: Thomas V.
=> production 20240131_allsky_v0.10.5_all_dec_base

production_configs/20240235_v0.10.5_dec_931_dec_min_2924_dec_3476/README.md, production_configs/20240235_v0.10.5_dec_931_dec_min_2924_dec_3476/lstchain_config_2024-02-05.json, production_configs/20240235_v0.10.5_dec_931_dec_min_2924_dec_3476/lstmcpipe_config_2024-02-05_PathConfigAllSkyFull.yaml
Base prod with missing declinations in 20240131_allsky_v0.10.5_all_dec_base
``` 
source /fefs/aswg/software/conda/etc/profile.d/conda.sh
conda activate lstchain-v0.10.5
lstmcpipe_generate_config PathConfigAllSkyFull --prod_id 20240131_allsky_v0.10.5_all_dec_base --dec_list dec_931 dec_min_2924 dec_3476  
```
=> prod 20240235_v0.10.5_dec_931_dec_min_2924_dec_3476

production_configs/20240126_v0.10.4_src6_dec2276_tuned/lstchain_config_20240126_v0.10.4_src6_dec2276_tuned.json, production_configs/20240126_v0.10.4_src6_dec2276_tuned/lstmcpipe_config_2024-01-26_PathConfigAllSkyFullDL1ab.yaml, production_configs/20240126_v0.10.4_src6_dec2276_tuned/readme.md
New Prod Config
20240126_v0.10.4_src6_dec2276_tuned
Config for the processing of MC at dec_2276 with NSB tuning to src6 and src-dependent configuration using a specific NSB tunning for the source.
Reprocess the data at declination 22.76 with version of lstchain v0.10.4 and with new tunning for new source: src6.
=> ask 20240126_v0.10.4_src6_dec2276_tuned production 

production_configs/20240122_v0.10.4_prod5_trans_80/lstchain_config_2024-01-22.json, production_configs/20240122_v0.10.4_prod5_trans_80/lstmcpipe_config_2024-01-22_PathConfigProd5Trans80.yaml, production_configs/20240122_v0.10.4_prod5_trans_80/readme.md
20240122_v0.10.4_prod5_trans80
lstmcpipe_generate_config PathConfigProd5Trans80 --prod_id v0.10.4_prod5_trans80
20 degrees for performance study
=> 20240122_v0.10.4_prod5_trans80

production_configs/20240219_allsky_v0.10.7_all_dec_srcdep_base/README.md, production_configs/20240219_allsky_v0.10.7_all_dec_srcdep_base/lstchain_config_2024-02-19_srcdep.json, production_configs/20240219_allsky_v0.10.7_all_dec_srcdep_base/lstmcpipe_config_2024-02-19_PathConfigAllTrainTestDL1b.yaml
20240219_allsky_v0.10.7_all_dec_srcdep_base production
Base production for all declinations lines with lstchain v0.10.7 & source-dependent approach
This production includes only training step and DL1 to DL2 step with existing training/test DL1 data
=> 20240219_allsky_v0.10.7_all_dec_srcdep_base production

lstmcpipe/scripts/lstmcpipe_generate_config.py
fixes #290 by introducing `--source_prod_id` for DL1ab type prods
Adding this arg should be less confusing to users.
=> add --source_prod_id as arg to generate config

production_configs/20240229_nsb14/lstchain_config_2024-02-29.json, production_configs/20240229_nsb14/lstmcpipe_config_2024-02-29_PathConfigAllSkyFullDL1ab.yaml, production_configs/20240229_nsb14/readme.md
20240229_dec34_nsb14
High NSB conditions (tuned on DL1a), cleaning (14, 7), training on 3476 dec line.
To analyze an interesting source in high NSB conditions...
=> Production for high NSB conditions and the 3476 dec line

production_configs/20240426_v0.10.9_src3_dec3476_4822_tunedNSB/README.md, production_configs/20240426_v0.10.9_src3_dec3476_4822_tunedNSB/lstchain_config_2024-04-26.json, production_configs/20240426_v0.10.9_src3_dec3476_4822_tunedNSB/lstmcpipe_config_2024-04-26_PathConfigAllSkyFull.yaml
20240426_v0.10.9_src3_dec3476_4822_tunedNSB
Config for a source with dec within 3476/4822 and NSB tuning:
"image_modifier": {
"increase_nsb": true,
"extra_noise_in_dim_pixels": 6.974,
"extra_bias_in_dim_pixels": 1.825,
"transition_charge": 8,
"extra_noise_in_bright_pixels": 4.195
}
lstmcpipe_generate_config PathConfigAllSkyFull --prod_id 20240426_v0.10.9_src3_dec3476_4822_tunedNSB --dec_list dec_3476 dec_4822
See wiki page (src 3)
https://www.lst1.iac.es/wiki/index.php/MC_analysis_and_IRF_production#lstmcpipe_productions
=> add new production for src3 with tuned NSB for moon data analysis

production_configs/20240716_v0.10.7_src10_dec3476_tuned/README.md, production_configs/20240716_v0.10.7_src10_dec3476_tuned/lstchain_config_2024-07-16.json, production_configs/20240716_v0.10.7_src10_dec3476_tuned/lstmcpipe_config_2024-07-16_PathConfigAllSkyFullDL1ab.yaml
20240716_v0.10.7_src10_dec3476_tuned
Config for reprocessing of Gamma Diffuse MC at declination line of 34.76 deg, based on 20240430_v0.10.4_src9$
NSB tuning adapted to the observed data of src10.
Need diffuse MC with tuning for new source: src10
=> add configs for prod 20240716_v0.10.7_src10_dec3476_tuned

production_configs/20240727_v0.10.11_src12_tuned/lstchain_config_2024-07-27.json, production_configs/20240727_v0.10.11_src12_tuned/lstmcpipe_config_2024-07-27_PathConfigAllSkyFullDL1ab.yaml, production_configs/20240727_v0.10.11_src12_tuned/readme.md
20240727_v0.10.11_src12_tuned
full DL1ab production (with NSB tuning for src12) with lstchain v0.10.11
NSB level was checked in the following way:
```
input_mc_base = Path("/fefs/aswg/data/mc/DL0/LSTProd2/TrainingDataset/GammaDiffuse/")
input_mc = input_mc_base / "dec_min_413/sim_telarray/node_corsika_theta_33.058_az_173.79_/output_v1.4/simtel_corsika_thet
a_33.058_az_173.79_run1.simtel.gz"
input_data_base = Path("/fefs/aswg/data/real/DL1/")
input_data = input_data_base / "20240701/v0.10/tailcut84/dl1_LST-1.Run17967.0000.h5"
print("this config was downloaded (and modified) on %s" % download_config_modified_time)
config_file = Path("./lstchain_standard_config.json")
!lstchain_tune_nsb --input-mc $input_mc --input-data $input_data --config $config_file
```
The resulting …
=> add production_configs/20240727_v0.10.11_src12_tuned

production_configs/20240917_v0.10.12_src15_dec_min_2924_tuned/README.md, production_configs/20240917_v0.10.12_src15_dec_min_2924_tuned/lstchain_config_2024-09-17.json, production_configs/20240917_v0.10.12_src15_dec_min_2924_tuned/lstmcpipe_config_2024-09-17_PathConfigAllSkyFullDL1ab.yaml
=> Add new configuration for src15
